export const Events = {
  PAGE_VIEW: "Page Viewed",
  LOGIN_SUCCESS: "Login Succeeded",
  LOGIN_FAILED: "Login Failed",
  LOGOUT: "Logout",
  SIGNUP_COMPLETED: "Signup Completed",
  SIGNUP_FAILED: "Signup Failed",
  INVITE_ACCEPTED: "Invite Accepted",
  INVITE_FAILED: "Invite Failed",
  CHALLAN_CREATED: "Challan Created",
  CHALLAN_UPDATED: "Challan Updated",
  CHALLAN_DELETED: "Challan Deleted",
  CHALLAN_BULK_DELETED: "Challans Bulk Deleted",
  CHALLAN_DELIVERED: "Challan Delivered",
  CHALLAN_PDF_DOWNLOADED: "Challan PDF Downloaded",
  CHALLAN_QR_VIEWED: "Challan QR Viewed",
  CHALLAN_OTP_SENT: "Challan OTP Sent",
  CHALLAN_OTP_VERIFIED: "Challan OTP Verified",
  EMAIL_NAMES_SAVED: "Email Sender Names Saved",
  EMAIL_TEST_SENT: "Test Email Sent",
  EMAIL_TEST_FAILED: "Test Email Failed",
  DESIGN_SETTINGS_SAVED: "Design Settings Saved",
  LOGO_UPLOADED: "Logo Uploaded",
  TERMS_SAVED: "Terms Saved",
  TEAM_USER_CREATED: "Team User Created",
  TEAM_USER_UPDATED: "Team User Updated",
  TEAM_USER_DELETED: "Team User Deleted",
  THEME_TOGGLED: "Theme Toggled",
  API_ERROR: "API Error",
  TENANT_CREATED: "Tenant Created",
  TENANT_UPDATED: "Tenant Updated",
  TENANT_DELETED: "Tenant Deleted",
  TENANT_INVITE_RESENT: "Tenant Invite Resent",
  SUBSCRIPTION_CREATED: "Subscription Created",
  ADMIN_TENANT_USER_CREATED: "Admin Tenant User Created",
  ADMIN_TENANT_USER_DELETED: "Admin Tenant User Deleted",
};
